# Generated by Django 4.1.5 on 2023-01-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_apartment_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['-created']},
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['-created'], name='scraper_apa_created_88feaa_idx'),
        ),
    ]
