# Generated by Django 4.1.5 on 2023-01-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_apartment_house_id_apartment_latitude_apartment_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='apartment',
            name='province',
            field=models.CharField(default='', max_length=50),
        ),
    ]
