# Generated by Django 4.1.5 on 2023-01-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_apartment_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='typology',
            field=models.CharField(default='', max_length=25),
        ),
    ]
